package missions;

import elements.Enemy;
import elements.Item;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class CollectNItemsMission extends SimpleInteractionMission {

    public static final String type = "item";

    public CollectNItemsMission(String targetId, int numInteractions) {
        super(targetId, numInteractions);
    }

    /**
     * @return the items population needed by the mission (id, number)
     */
    @Override
    public Map<String, Integer> getItemPopulation() {
        return getNeeded();
    }

    /**
     * @return the item set generated by the mission
     */
    @Override
    public Set<Item> getItemSet() {
        return new HashSet<>();
    }

    /**
     * @return the enemies population needed by the mission (id, number)
     */
    @Override
    public Map<String, Integer> getEnemyPopulation() {
        return new HashMap<>();
    }

    /**
     * @return the mob set generated by the mission
     */
    @Override
    public Set<Enemy> getEnemySet() {
        return new HashSet<>();
    }

    @Override
    public String toString(){
        return "You have to collect " + getNumInteractions() + " " + getTargetId();
    }
}
