package missions;

import elements.Enemy;
import org.newdawn.slick.tests.xml.Item;

import java.util.Set;

/**
 * The composite mission list defines all the elements to manage the missions as a composite architecture
 */
public interface Mission {

    /**
     * Adds a mission to the list
     * @param e the mission to add
     */
    void add(Mission e);

    /**
     * @return true if the mission was completed, false otherwise
     */
    boolean completed();

    /**
     * (TO BE REFEACTORED)
     */
    void check();

    /**
     * @return the item set generated by the mission
     */
    Set<Item> getItemSet();

    /**
     * @return the mob set generated by the mission
     */
    Set<Enemy> geItemSet();
}
